version: "3.9"
services:
  upage:
    depends_on:
      postgres:
        condition: service_healthy
    image: upage-ai:dev
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - OPERATING_ENV=${OPERATING_ENV:-production}
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=postgres://upage:${POSTGRES_PASSWORD}@postgres:5432/upage?schema=upage_schema
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - OPENAI_LIKE_API_BASE_URL=${OPENAI_LIKE_API_BASE_URL}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_LIKE_API_KEY=${OPENAI_LIKE_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - HYPERBOLIC_API_KEY=${HYPERBOLIC_API_KEY}
      - HYPERBOLIC_API_BASE_URL=${HYPERBOLIC_API_BASE_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - LMSTUDIO_API_BASE_URL=${LMSTUDIO_API_BASE_URL}
      - XAI_API_KEY=${XAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - AWS_BEDROCK_CONFIG=${AWS_BEDROCK_CONFIG}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - LLM_DEFAULT_PROVIDER=${LLM_DEFAULT_PROVIDER}
      - LLM_DEFAULT_MODEL=${LLM_DEFAULT_MODEL}
      - LLM_MINOR_MODEL=${LLM_MINOR_MODEL}
      - LLM_ENABLED_PROVIDERS=${LLM_ENABLED_PROVIDERS}
      - LOGTO_ENDPOINT=${LOGTO_ENDPOINT}
      - LOGTO_APP_ID=${LOGTO_APP_ID}
      - LOGTO_APP_SECRET=${LOGTO_APP_SECRET}
      - LOGTO_COOKIE_SECRET=${LOGTO_COOKIE_SECRET}
      - LOGTO_BASE_URL=${LOGTO_BASE_URL}
      - LOGTO_ENABLE_DEV=${LOGTO_ENABLE_DEV:-false}
      - USAGE_LOG_FILE=true
      - STORAGE_DIR=/app/storage
      - MAX_UPLOAD_SIZE_MB=${MAX_UPLOAD_SIZE_MB:-5}
    networks:
      upage_network:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: upage
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      upage_network:

networks:
  upage_network:

volumes:
  upage-db:
